name: deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

concurrency: ${{ inputs.environment }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3
      - name: deploy
        run: |
          echo "running deploy of ${{ github.run_number }}-${{ github.run_id }} to ${{ inputs.environment }}..."
          sleep 2
          echo "deploy done"
  test-1:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          echo "running test-1"
          sleep 2
          echo "done"
  test-2:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          echo "running test-2"
          sleep 2
          echo "done"
