name: pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: install deps
        run: npm ci
      - name: build
        run: |
          echo "running build..."
          sleep 10
          echo "build done"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: install deps
        run: npm ci
      - name: test
        run: |
          echo "running test..."
          sleep 10
          echo "test done"
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: install deps
        run: npm ci
      - name: lint
        run: |
          echo "running lint..."
          sleep 10
          echo "lint done"

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test, lint]
    steps:
      - uses: actions/checkout@v3
      - name: deploy
        run: |
          echo "running deploy..."
          sleep 20
          echo "deploy done"
