name: pipeline

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/run-in-container
        name: build
        with:
          command: |
            echo "running build..."
            sleep 2
            echo "build done"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/run
        name: test
        with:
          command: |
            npm ci
            echo "running test..."
            sleep 2
            echo "test done"
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/run
        name: lint
        with:
          command: |
            npm ci
            echo "running lint..."
            sleep 2
            echo "lint done"

  deploy-to-test:
    needs: [build, test, lint]
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: test

  deploy-to-stage:
    needs: [deploy-to-test]
    uses: ./.github/workflows/deploy.yml
    with:
      environment: stage

  deploy-to-prod:
    needs: [deploy-to-stage]
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
